"""MCP tool for routing an externally-provided (e.g. PG-DiGress) graph."""

from __future__ import annotations

import json
from datetime import datetime, timezone

from mcp.server import MCPServer
from mcp.server.mcpserver.context import Context

from shift.mcp_server.state import AppContext, GraphMeta
from shift.mcp_server.serializers import serialize_graph_summary


def register(mcp: MCPServer) -> None:
    @mcp.tool()
    def route_existing_graph(
        ctx: Context[AppContext],
        candidate_graphs_path: str,
        source_longitude: float,
        source_latitude: float,
        graph_index: int = 0,
        parcels: list[dict] | None = None,
        groups: list[dict] | None = None,
        source_node_index: int | None = None,
        relaxation_iterations: int = 250,
        use_road_network: bool = False,
        routing_strategy: str = "mst",
        topology_bias: float = 0.7,
        name: str = "",
    ) -> str:
        """Route an existing abstract graph onto parcel geography.

        Takes a topology generated by an external tool (typically a PG-DiGress
        JSON export) and embeds it into geographic space using parcel locations
        and a chosen substation location, producing a DistributionGraph that can
        be mapped and built into a GDM system.

        Args:
            candidate_graphs_path: Path to a PG-DiGress JSON export
                (see the DiGress ``export_candidate_graph_json`` tool).
            source_longitude: Longitude of the voltage source (substation).
            source_latitude: Latitude of the voltage source (substation).
            graph_index: Which graph within the export to route (default 0).
            parcels: List of parcel locations ``[{longitude, latitude}, ...]``.
                Either ``parcels`` or ``groups`` must be provided.
            groups: Alternatively, cluster groups ``[{center, points}, ...]``;
                their points are flattened into parcel locations.
            source_node_index: Force a specific abstract node to be the source.
                Auto-detected from labels/degree when omitted.
            relaxation_iterations: Laplacian smoothing iterations for junction
                placement (default 250).
            use_road_network: Route the source and loads over the OSM road
                network so feeders follow real streets (default False).
            routing_strategy: Road-routing strategy when ``use_road_network`` is
                set: ``"mst"`` (default), ``"shortest_path"``, ``"steiner"``, or
                ``"biased"`` -- a DiGress-biased Steiner tree that follows roads
                while hugging the generated topology's corridors.
            topology_bias: Strength (0..1) of the generated-topology bias for the
                ``"biased"`` strategy (default 0.7; 0 = pure shortest road path).
            name: Optional name for the created graph.

        Returns:
            JSON with graph_id and a summary of the created graph.
        """
        try:
            from shift.data_model import GeoLocation
            from shift.graph.existing_graph_router import (
                AbstractGraph,
                ExistingGraphRouter,
            )

            app: AppContext = ctx.request_context.lifespan_context

            parcel_points: list[GeoLocation] = []
            if parcels:
                parcel_points.extend(GeoLocation(p["longitude"], p["latitude"]) for p in parcels)
            if groups:
                for g in groups:
                    for p in g.get("points", []):
                        parcel_points.append(GeoLocation(p["longitude"], p["latitude"]))

            if not parcel_points:
                return json.dumps(
                    {
                        "success": False,
                        "error": "Provide 'parcels' or 'groups' with at least one point.",
                    }
                )

            abstract = AbstractGraph.from_json_file(candidate_graphs_path, graph_index=graph_index)
            router = ExistingGraphRouter(
                abstract_graph=abstract,
                parcels=parcel_points,
                source_location=GeoLocation(source_longitude, source_latitude),
                source_node_index=source_node_index,
                relaxation_iterations=relaxation_iterations,
                use_road_network=use_road_network,
                routing_strategy=routing_strategy,
                topology_bias=topology_bias,
            )
            dist_graph = router.get_distribution_graph()

            graph_id = app.generate_id()
            app.graphs[graph_id] = dist_graph
            app.graph_meta[graph_id] = GraphMeta(
                name=name or f"routed-{graph_id}",
                created_at=datetime.now(timezone.utc).isoformat(),
            )
            app.refresh_graph_meta(graph_id)

            return json.dumps(
                {
                    "success": True,
                    "graph_index": graph_index,
                    "num_abstract_nodes": abstract.num_nodes,
                    "num_parcels": len(parcel_points),
                    **serialize_graph_summary(dist_graph, graph_id, app.graph_meta[graph_id]),
                }
            )

        except Exception as exc:
            return json.dumps({"success": False, "error": str(exc)})
