"""Route an externally-provided abstract graph onto real parcel geography.

This module adds the "route an existing graph" capability to SHIFT. Unlike the
road-based builders (:class:`~shift.graph.prsgb.PRSG`) that *construct* a topology
from an OpenStreetMap road network, this router takes a topology that already
exists -- typically a graph generated by the PG-DiGress diffusion model -- and
embeds it into geographic space using the parcel locations and a chosen
substation location.

Pipeline
--------
1. Parse an abstract topology (nodes with categorical classes + edges with
   categorical classes). No geographic coordinates are assumed.
2. Assign *roles* to nodes (source / load / junction) from their class labels,
   with degree-based fallbacks.
3. Anchor the source node at the substation location and the load nodes at
   parcel-cluster centers, then place the remaining (junction) nodes with
   anchored Laplacian relaxation so the embedding respects the topology.
4. Convert the geolocated graph into a :class:`DistributionGraph` (reusing the
   existing conversion + transformer-explosion machinery) that the SHIFT
   mappers and system builder can consume unchanged.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path

import networkx as nx
from gdm.distribution.components import DistributionLoad, DistributionVoltageSource
from infrasys.quantities import Distance
from loguru import logger

from shift.data_model import GeoLocation, GroupModel, VALID_NODE_TYPES
from shift.exceptions import EmptyGraphError, InvalidInputError
from shift.graph.distribution_graph import DistributionGraph
from shift.graph.openstreet_graph_builder import OpenStreetGraphBuilder
from shift.utils.get_cluster import get_kmeans_clusters


# Keywords used to infer node roles from PG-DiGress class labels.
_SOURCE_KEYWORDS = ("source", "substation", "slack", "feeder", "grid", "swing")
_LOAD_KEYWORDS = ("load", "consumer", "demand", "customer", "house", "residential")


@dataclass
class AbstractGraph:
    """A geometry-free topology produced by an external generator.

    Parameters
    ----------
    num_nodes : int
        Number of nodes in the graph.
    edges : list[tuple[int, int]]
        Active (non-"no-edge") undirected edges as index pairs.
    node_classes : list[int], optional
        Per-node categorical class index (aligned with ``node_labels``).
    node_labels : list[str], optional
        Human-readable name for each node class index.
    edge_classes : list[int], optional
        Per-edge categorical class index (aligned with ``edge_labels``).
    edge_labels : list[str], optional
        Human-readable name for each edge class index.
    """

    num_nodes: int
    edges: list[tuple[int, int]]
    node_classes: list[int] | None = None
    node_labels: list[str] | None = None
    edge_classes: list[int] | None = None
    edge_labels: list[str] | None = None

    def __post_init__(self) -> None:
        if self.num_nodes <= 0:
            raise InvalidInputError(f"num_nodes must be positive, got {self.num_nodes}.")
        for u, v in self.edges:
            if not (0 <= u < self.num_nodes and 0 <= v < self.num_nodes):
                raise InvalidInputError(
                    f"Edge ({u}, {v}) references a node outside [0, {self.num_nodes})."
                )

    @classmethod
    def from_export(cls, export: dict, graph_index: int = 0) -> "AbstractGraph":
        """Build from a PG-DiGress JSON export payload.

        The expected schema is::

            {
              "metadata": {"node_labels": [...], "edge_labels": [...]},
              "graphs": [
                {"graph_index": 0, "num_nodes": N,
                 "node_classes": [...N...],
                 "edges": [[i, j, edge_class], ...]},
                ...
              ]
            }

        Parameters
        ----------
        export : dict
            Parsed JSON export.
        graph_index : int
            Index of the graph to extract from ``export["graphs"]``.
        """
        graphs = export.get("graphs")
        if not graphs:
            raise InvalidInputError("Export payload contains no 'graphs'.")
        if not (0 <= graph_index < len(graphs)):
            raise InvalidInputError(
                f"graph_index {graph_index} out of range (have {len(graphs)} graphs)."
            )

        entry = graphs[graph_index]
        metadata = export.get("metadata", {})
        raw_edges = entry.get("edges", [])

        edges: list[tuple[int, int]] = []
        edge_classes: list[int] = []
        for item in raw_edges:
            if len(item) >= 3:
                i, j, edge_cls = int(item[0]), int(item[1]), int(item[2])
            else:
                i, j, edge_cls = int(item[0]), int(item[1]), 1
            edges.append((i, j))
            edge_classes.append(edge_cls)

        node_classes = entry.get("node_classes")
        return cls(
            num_nodes=int(entry.get("num_nodes", 0))
            or (max((max(e) for e in edges), default=-1) + 1),
            edges=edges,
            node_classes=[int(c) for c in node_classes] if node_classes is not None else None,
            node_labels=list(metadata.get("node_labels")) if metadata.get("node_labels") else None,
            edge_classes=edge_classes or None,
            edge_labels=list(metadata.get("edge_labels")) if metadata.get("edge_labels") else None,
        )

    @classmethod
    def from_json_file(cls, path: str | Path, graph_index: int = 0) -> "AbstractGraph":
        """Load an :class:`AbstractGraph` from a PG-DiGress JSON export file."""
        payload = json.loads(Path(path).read_text(encoding="utf-8"))
        return cls.from_export(payload, graph_index=graph_index)

    # -- role helpers ---------------------------------------------------------
    def _label_for_node(self, idx: int) -> str:
        if self.node_classes is None or self.node_labels is None:
            return ""
        if not (0 <= idx < len(self.node_classes)):
            return ""
        cls = self.node_classes[idx]
        if 0 <= cls < len(self.node_labels):
            return str(self.node_labels[cls]).lower()
        return ""


class NodeRoles:
    """Resolved source / load / junction roles for an :class:`AbstractGraph`."""

    def __init__(self, source: int, loads: list[int], junctions: list[int]):
        self.source = source
        self.loads = loads
        self.junctions = junctions


def resolve_node_roles(
    abstract: AbstractGraph,
    graph: nx.Graph,
    source_node_index: int | None = None,
) -> NodeRoles:
    """Assign source / load / junction roles to abstract-graph nodes.

    Role inference order:

    * **Source** -- explicit ``source_node_index`` > label keyword match >
      highest-degree node.
    * **Loads** -- label keyword match > degree-1 leaf nodes (excluding source).
    * **Junctions** -- everything else.
    """
    nodes = list(range(abstract.num_nodes))

    # Source
    if source_node_index is not None:
        if not (0 <= source_node_index < abstract.num_nodes):
            raise InvalidInputError(
                f"source_node_index {source_node_index} out of range [0, {abstract.num_nodes})."
            )
        source = source_node_index
    else:
        labelled_sources = [
            n for n in nodes if any(k in abstract._label_for_node(n) for k in _SOURCE_KEYWORDS)
        ]
        if labelled_sources:
            source = max(labelled_sources, key=lambda n: graph.degree(n))
        else:
            source = max(nodes, key=lambda n: graph.degree(n)) if graph.number_of_edges() else 0

    # Loads
    labelled_loads = [
        n
        for n in nodes
        if n != source and any(k in abstract._label_for_node(n) for k in _LOAD_KEYWORDS)
    ]
    if labelled_loads:
        loads = labelled_loads
    else:
        loads = [n for n in nodes if n != source and graph.degree(n) == 1]
    if not loads:
        # Degenerate topology (e.g. a single cycle): treat every non-source node
        # as a load so the built system still has demand.
        loads = [n for n in nodes if n != source]

    load_set = set(loads)
    junctions = [n for n in nodes if n != source and n not in load_set]
    return NodeRoles(source=source, loads=loads, junctions=junctions)


class ExistingGraphRouter(OpenStreetGraphBuilder):
    """Embed an abstract topology onto parcel geography and build a graph.

    Parameters
    ----------
    abstract_graph : AbstractGraph
        Geometry-free topology to route (e.g. a PG-DiGress sample).
    parcels : list[GeoLocation]
        Parcel locations used as geographic anchors for load nodes.
    source_location : GeoLocation
        Substation / voltage-source location chosen by the user.
    source_node_index : int, optional
        Force a specific abstract node to be the source. Auto-detected otherwise.
    relaxation_iterations : int
        Number of Laplacian smoothing iterations used to place junction nodes.

    Examples
    --------
    >>> router = ExistingGraphRouter(abstract, parcels, GeoLocation(-97.33, 32.75))
    >>> dist_graph = router.get_distribution_graph()
    """

    def __init__(
        self,
        abstract_graph: AbstractGraph,
        parcels: list[GeoLocation],
        source_location: GeoLocation,
        source_node_index: int | None = None,
        relaxation_iterations: int = 250,
        use_road_network: bool = False,
        routing_strategy: str = "mst",
    ):
        # groups are not used by this builder; pass an empty list to the base.
        super().__init__(groups=[], source_location=source_location)
        if not parcels:
            raise InvalidInputError("At least one parcel location is required.")
        self.abstract_graph = abstract_graph
        self.parcels = parcels
        self.source_node_index = source_node_index
        self.relaxation_iterations = max(0, int(relaxation_iterations))
        self.use_road_network = bool(use_road_network)
        self.routing_strategy = str(routing_strategy or "mst").lower()
        self._roles: NodeRoles | None = None
        self._load_node_names: list[str] = []
        self._source_node_name: str = ""

    def _road_candidate_graph(self, anchors: dict[int, GeoLocation]) -> "nx.Graph | None":
        """Fetch the OSM road network covering the anchors as a routing candidate.

        Returns the largest connected component with string node ids and x/y
        attributes, or ``None`` when no road data is available.
        """
        from shift.openstreet_roads import get_road_network

        lons = [loc.longitude for loc in anchors.values()]
        lats = [loc.latitude for loc in anchors.values()]
        pad = 0.003
        polygon = [
            GeoLocation(min(lons) - pad, min(lats) - pad),
            GeoLocation(max(lons) + pad, min(lats) - pad),
            GeoLocation(max(lons) + pad, max(lats) + pad),
            GeoLocation(min(lons) - pad, max(lats) + pad),
        ]
        try:
            road = get_road_network(polygon, Distance(100, "m"), reduce_to_mst=False)
        except Exception as exc:  # noqa: BLE001
            logger.warning(f"Road-network fetch failed: {exc}")
            return None
        if road is None or road.number_of_nodes() == 0:
            return None
        if isinstance(road, (nx.MultiGraph, nx.MultiDiGraph)):
            road = nx.Graph(road)
        components = list(nx.connected_components(road))
        if components:
            road = road.subgraph(max(components, key=len)).copy()
        return nx.relabel_nodes(road, {n: f"r{n}" for n in road.nodes})

    def _route_over_roads(self):
        """Route the source and load anchors over the road network with a SHIFT
        routing strategy, producing a clean tree that follows streets.

        Returns ``(tree, load_names, source_name)`` or ``None`` to fall back to
        the relaxation embedding.
        """
        from shift.graph.routing import (
            MinimumSpanningTreeStrategy,
            ShortestPathTreeStrategy,
            WeightedSteinerTreeStrategy,
        )

        graph = self._build_nx()
        roles = resolve_node_roles(self.abstract_graph, graph, self.source_node_index)
        self._roles = roles
        anchors = self._anchor_positions(graph, roles)

        road = self._road_candidate_graph(anchors)
        if road is None:
            return None
        road_nodes = [
            (n, d["x"], d["y"]) for n, d in road.nodes(data=True) if "x" in d and "y" in d
        ]
        if not road_nodes:
            return None

        def nearest(loc: GeoLocation) -> str:
            return min(
                road_nodes, key=lambda r: (r[1] - loc.longitude) ** 2 + (r[2] - loc.latitude) ** 2
            )[0]

        source_name = nearest(anchors[roles.source])
        load_names = list(dict.fromkeys(nearest(anchors[load]) for load in roles.loads))
        load_names = [n for n in load_names if n != source_name] or load_names
        terminals = list(dict.fromkeys([source_name, *load_names]))
        if len(terminals) < 2:
            return None

        strategies = {
            "mst": MinimumSpanningTreeStrategy,
            "shortest_path": ShortestPathTreeStrategy,
            "steiner": lambda: WeightedSteinerTreeStrategy(crossing_penalty=3.0),
        }
        factory = strategies.get(self.routing_strategy, MinimumSpanningTreeStrategy)
        try:
            tree = factory().route(road, terminals)
        except Exception as exc:  # noqa: BLE001
            logger.warning(f"Road routing ({self.routing_strategy}) failed: {exc}")
            return None

        self._source_node_name = source_name
        self._load_node_names = load_names
        logger.info(
            f"Routed {len(load_names)} loads + source over roads "
            f"({self.routing_strategy}) -> {tree.number_of_nodes()} nodes, "
            f"{tree.number_of_edges()} edges."
        )
        return tree, load_names, source_name

    def _build_road_distribution_graph(
        self, tree: "nx.Graph", load_names: list[str], source_name: str
    ) -> DistributionGraph:
        """Turn a road-routed tree into a DistributionGraph.

        The routed tree is the *primary* network (source + road junctions). Each
        load anchor keeps its place on the primary and a distribution load is
        hung off it as a leaf; the shared transformer-explosion machinery then
        inserts a single-phase HT tap + transformer between the primary junction
        and the load, so the HT/LT voltage and phase step are well-defined.
        """
        final = nx.Graph()
        for name, data in tree.nodes(data=True):
            final.add_node(name, x=float(data["x"]), y=float(data["y"]))
        for u, v in tree.edges:
            final.add_edge(u, v)

        load_leaves: list[str] = []
        for anchor in load_names:
            data = tree.nodes[anchor]
            leaf = f"{anchor}_load"
            final.add_node(leaf, x=float(data["x"]) + 1e-6, y=float(data["y"]) + 1e-6)
            final.add_edge(anchor, leaf)
            load_leaves.append(leaf)

        asset_nodes: dict[VALID_NODE_TYPES, list[str]] = {
            DistributionLoad: load_leaves,
            DistributionVoltageSource: [source_name],
        }
        # Load leaves become transformer nodes so the explosion inserts a
        # single-phase HT tap + transformer upstream of each load.
        return self._get_distribution_graph_from_network(final, load_leaves, asset_nodes)

    # -- abstract API required by OpenStreetGraphBuilder ----------------------
    def build_secondary_network(self, group: GroupModel) -> nx.Graph:  # noqa: D102
        raise NotImplementedError(
            "ExistingGraphRouter does not build secondary networks; the abstract "
            "topology already encodes connectivity."
        )

    def build_primary_network(self) -> nx.Graph:
        """Return the abstract topology embedded into geographic space."""
        return self._embed()

    # -- embedding ------------------------------------------------------------
    def _build_nx(self) -> nx.Graph:
        graph = nx.Graph()
        graph.add_nodes_from(range(self.abstract_graph.num_nodes))
        graph.add_edges_from(self.abstract_graph.edges)
        return graph

    def _ensure_connected(self, graph: nx.Graph, source: int) -> None:
        """Attach disconnected components to the source component (in place)."""
        if graph.number_of_nodes() <= 1:
            return
        components = list(nx.connected_components(graph))
        if len(components) == 1:
            return
        source_component = next((c for c in components if source in c), components[0])
        anchor = source if source in source_component else next(iter(source_component))
        for component in components:
            if component is source_component or (source in component):
                continue
            graph.add_edge(anchor, next(iter(component)))
        logger.info(
            f"Connected {len(components) - 1} isolated component(s) to the source component."
        )

    def _anchor_positions(self, graph: nx.Graph, roles: NodeRoles) -> dict[int, GeoLocation]:
        """Compute fixed geographic anchors for the source and load nodes."""
        anchors: dict[int, GeoLocation] = {roles.source: self.source_location}

        loads = roles.loads
        if not loads:
            return anchors

        k = min(len(loads), len(self.parcels))
        clusters = get_kmeans_clusters(k, self.parcels)
        centers = [c.center for c in clusters]

        # Assign each load node a distinct cluster center where possible; if there
        # are more load nodes than clusters, reuse centers round-robin.
        for i, load in enumerate(loads):
            anchors[load] = centers[i % len(centers)]
        return anchors

    def _embed(self) -> nx.Graph:
        abstract = self.abstract_graph
        graph = self._build_nx()

        roles = resolve_node_roles(abstract, graph, self.source_node_index)
        self._roles = roles
        self._ensure_connected(graph, roles.source)

        anchors = self._anchor_positions(graph, roles)

        # Initialise every node at the centroid of the anchors.
        cx = sum(loc.longitude for loc in anchors.values()) / len(anchors)
        cy = sum(loc.latitude for loc in anchors.values()) / len(anchors)
        pos: dict[int, list[float]] = {}
        for node in graph.nodes:
            if node in anchors:
                pos[node] = [anchors[node].longitude, anchors[node].latitude]
            else:
                pos[node] = [cx, cy]

        # Anchored Laplacian relaxation: free nodes move to the mean of their
        # neighbours while anchors stay fixed. Converges to a topology-respecting
        # geographic layout.
        free_nodes = [n for n in graph.nodes if n not in anchors]
        for _ in range(self.relaxation_iterations):
            max_delta = 0.0
            for node in free_nodes:
                neighbors = list(graph.neighbors(node))
                if not neighbors:
                    continue
                nx_ = sum(pos[m][0] for m in neighbors) / len(neighbors)
                ny_ = sum(pos[m][1] for m in neighbors) / len(neighbors)
                max_delta = max(max_delta, abs(nx_ - pos[node][0]), abs(ny_ - pos[node][1]))
                pos[node] = [nx_, ny_]
            if max_delta < 1e-9:
                break

        # Relabel integer node ids to stable unique string names and write coords.
        embedded = nx.Graph()
        name_of: dict[int, str] = {n: f"n{n}" for n in graph.nodes}
        self._source_node_name = name_of[roles.source]
        self._load_node_names = [name_of[n] for n in roles.loads]
        for node in graph.nodes:
            embedded.add_node(name_of[node], x=pos[node][0], y=pos[node][1])
        for u, v in graph.edges:
            embedded.add_edge(name_of[u], name_of[v])
        return embedded

    # -- public build ---------------------------------------------------------
    def get_distribution_graph(self) -> DistributionGraph:
        """Build a :class:`DistributionGraph` from the routed abstract topology."""
        # Road-network routing: connect the source + load anchors over the real
        # street grid with a SHIFT routing strategy (MST / Steiner / shortest
        # path). Produces a clean, geographically-sensible radial feeder instead
        # of the straight-line abstract edges.
        if self.use_road_network:
            routed = self._route_over_roads()
            if routed is not None:
                tree, load_names, source_name = routed
                return self._build_road_distribution_graph(tree, load_names, source_name)
            logger.warning("Road routing unavailable; using relaxation embedding.")

        embedded = self.build_primary_network()
        if not embedded.nodes:
            raise EmptyGraphError("Routing produced an empty graph.")

        asset_nodes = {
            DistributionLoad: list(self._load_node_names),
            DistributionVoltageSource: [self._source_node_name],
        }
        # Load-serving nodes become transformer nodes so a distribution
        # transformer is inserted upstream of each load (matching SHIFT's
        # primary/secondary convention).
        transformer_nodes = list(self._load_node_names)
        return self._get_distribution_graph_from_network(embedded, transformer_nodes, asset_nodes)
